-- +goose Up
CREATE TABLE acquisition_script (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    draft_source TEXT NOT NULL DEFAULT '',
    published_version_id BIGINT,
    create_by BIGINT,
    update_by BIGINT,
    create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_acquisition_script_name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT ck_acquisition_script_deleted CHECK (deleted IN (0, 1))
);
CREATE UNIQUE INDEX uk_acquisition_script_name ON acquisition_script (name) WHERE deleted = 0;

CREATE TABLE acquisition_script_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_id BIGINT NOT NULL REFERENCES acquisition_script (id) ON DELETE RESTRICT,
    version_no INTEGER NOT NULL CHECK (version_no > 0),
    source TEXT NOT NULL,
    checksum VARCHAR(64) NOT NULL CHECK (checksum ~ '^[0-9A-Fa-f]{64}$'),
    published_by BIGINT NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (script_id, version_no),
    UNIQUE (script_id, id)
);
ALTER TABLE acquisition_script ADD CONSTRAINT fk_acquisition_script_published_version
    FOREIGN KEY (id, published_version_id) REFERENCES acquisition_script_version (script_id, id);
ALTER TABLE acquisition_device ADD COLUMN script_id BIGINT REFERENCES acquisition_script (id) ON DELETE RESTRICT;
CREATE INDEX idx_acquisition_device_script ON acquisition_device (script_id);

-- +goose StatementBegin
CREATE FUNCTION acquisition_script_version_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'script versions are immutable';
END;
$$;
-- +goose StatementEnd
CREATE TRIGGER acquisition_script_version_immutable BEFORE UPDATE OR DELETE ON acquisition_script_version
FOR EACH ROW EXECUTE FUNCTION acquisition_script_version_immutable();

-- +goose Down
DROP TRIGGER acquisition_script_version_immutable ON acquisition_script_version;
DROP FUNCTION acquisition_script_version_immutable();
ALTER TABLE acquisition_device DROP COLUMN script_id;
ALTER TABLE acquisition_script DROP CONSTRAINT fk_acquisition_script_published_version;
DROP TABLE acquisition_script_version;
DROP TABLE acquisition_script;
